# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# This workflow automatically styles R source files using styler with Bioconductor conventions.
# It runs on push or pull requests that modify R-related files and commits changes back to the branch.
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: Apply Bioconductor Style to R Code

on:
  push:
    branches:
      - main
    paths:
      - "**.[rR]"
      - "**.[qrR]md"
      - "**.[rR]markdown"
      - "**.[rR]nw"
      - "**.[rR]profile"

  pull_request:
    paths:
      - "**.[rR]"
      - "**.[qrR]md"
      - "**.[rR]markdown"
      - "**.[rR]nw"
      - "**.[rR]profile"

permissions: read-all

jobs:
  style:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install styler, biocthis, and roxygen2
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: styler, biocthis, roxygen2

      - name: Enable styler cache
        run: styler::cache_activate()
        shell: Rscript {0}

      - name: Determine cache location
        id: styler-location
        run: |
          cat(
            "location=",
            styler::cache_info(format = "tabular")$location,
            "\n",
            file = Sys.getenv("GITHUB_OUTPUT"),
            append = TRUE,
            sep = ""
          )
        shell: Rscript {0}

      - name: Cache styler
        uses: actions/cache@v4
        with:
          path: ${{ steps.styler-location.outputs.location }}
          key: ${{ runner.os }}-styler-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-styler-
            ${{ runner.os }}-

      - name: Style
        run: styler::style_pkg(transformers = biocthis::bioc_style())
        shell: Rscript {0}

      - name: Commit and push changes
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref || github.ref_name }}
        run: |
          FILES_TO_COMMIT=$(git diff --name-only | grep -Ei '\.(r|[qr]md|rmarkdown|rnw|rprofile)$' || true)
          if [ -n "$FILES_TO_COMMIT" ]; then
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            echo "$FILES_TO_COMMIT" | xargs -r git add
            git commit -m "Style code (GHA)"
            git push origin HEAD:"$GITHUB_HEAD_REF"
          else
            echo "No changes to commit."
          fi